apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rgv0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0070-tenant/ci10t-786-0070-app/devfile-sample-rgv0@sha256:dda626dd412385d3ec8aeaaaa81832095285f44a22446ba88636c131ef0b98be
        name: my-nodejs
        resources: {}
status: {}
